services:
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=stock      
    ports:
      - "5432:5432"
    volumes:
      - /postgres-data:/var/lib/postgresql/data  

  app:
    image: golang:1.22
    command:
      - go
      - run
      - main.go
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres #nome do serviço do banco de dados
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_NAME=admin
      - DB_PORT=5432  