version: '3.4'

services:
  server:
    image: ${DOCKER_REGISTRY-}server
    build:
      context: .
      dockerfile: Server/Dockerfile
    ports:
      - "5100:5100"
      - "7200:7200"

  # sonarqube:
  #   image: sonarqube:community
  #   depends_on:
  #     - stock.database
  #   environment:
  #     SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
  #     SONAR_JDBC_USERNAME: sonar
  #     SONAR_JDBC_PASSWORD: sonar
  #   volumes:
  #     - sonarqube_data:/opt/sonarqube/data
  #     - sonarqube_extensions:/opt/sonarqube/extensions
  #     - sonarqube_logs:/opt/sonarqube/logs
  #   ports:
  #     - "9000:9000"

  stock.database:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=stock      
    ports:
      - 5432:5432
    volumes:
      - /postgres-data:/var/lib/postgresql/data  

# volumes:
#     sonarqube_data:
#     sonarqube_extensions:
#     sonarqube_logs:
#     postgresql:
#     postgresql_data:
    
  
